repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.96.3
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint
    - id: terraform_tfsec
    - id: terraform_checkov
    - id: terraform_trivy
    - id: tfupdate
    # - id: infracost_breakdown
